### ISSUE TITLE
recorder wont ignore dwains theme domain and errors inserting

### ISSUE THREAD

**Issue by whatdaybob** [dwainscheeren/lovelace-dwains-theme#123]
Every time I get a notification via the Dwains theme notify I have the below error in my logs that spam it almost every second.

I have tried excluding the domain and the entities themselves.

```
2020-05-05 04:30:00 ERROR (Recorder) [homeassistant.components.recorder] Error adding event: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_type' at row 1")
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: ('dwains_theme_notifications_updated', '{}', 'LOCAL', datetime.datetime(2020, 5, 5, 4, 30, 0, 330429, tzinfo=<UTC>), datetime.datetime(2020, 5, 5, 4, 30, 0, 353587), 'ffb1f80397634d07909f93725a5e7e67', None)]
(Background on this error at: http://sqlalche.me/e/9h9h) (Background on this error at: http://sqlalche.me/e/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 372, in run
    self.event_session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2592, in _flush
    subtransactions=True
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 947, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 316, in _begin
    self._assert_active()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
    code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_type' at row 1")
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: ('dwains_theme_notifications_updated', '{}', 'LOCAL', datetime.datetime(2020, 5, 5, 4, 30, 0, 330429, tzinfo=<UTC>), datetime.datetime(2020, 5, 5, 4, 30, 0, 353587), 'ffb1f80397634d07909f93725a5e7e67', None)]
(Background on this error at: http://sqlalche.me/e/9h9h) (Background on this error at: http://sqlalche.me/e/7s2a)
``` 

the only notifications I have setup are the below and I believe it all looks ok, the one it seems to fail on is ID 1 which failed with the notification '0.109.4 is available for download' but still shows in the dwains theme dashboard.

```
      - service: dwains_theme.notification_create
        data_template:
          message: "{{states('sensor.ha_version_docker_stable') | string }} is available for download" 
          notification_id: '1'
```
```
      - service: dwains_theme.notification_create
        data_template:
          message: "Device joined the zigbee2mqtt network,
                    Name: {{trigger.payload_json.meta.friendly_name}},
                    Vendor: {{trigger.payload_json.meta.vendor}},
                    Description: {{trigger.payload_json.meta.description}}"
          notification_id: '2'
```
```
      - service: dwains_theme.notification_create
        data_template:
          message: "{{states('sensor.zigbee2mqtt_github_version') | string }} is available for download" 
          notification_id: '3'
```

**Comment by dwainscheeren** [comment]
Still got these errors?

**Comment by whatdaybob** [comment]
Sorry, I removed the theme as I updated my home assistant to the latest version and the theme was not compatible. You may close this as it seems I may have been the only person experiencing this.
